FROM node:20

WORKDIR /app

COPY ["package.json", "pnpm-lock.yaml", "/app/"]

RUN npm install -g pnpm
RUN pnpm install
RUN npm install -g prisma

# Copie du reste des fichiers de l'application dans le conteneur
COPY . .

RUN ["pnpm", "prisma", "migrate"]

CMD ["pnpm", "run", "dev"]